### ISSUE TITLE
Generated correction symbols are not the same as in MATLAB

### ISSUE THREAD

**Issue by DmitryYenkov** [raeudigerRaeffi/generalizedReedSolomon#1]
![image](https://github.com/raeudigerRaeffi/generalizedReedSolomon/assets/21358654/3accd780-c91b-4ae4-8de9-8d706bd85e30)
![image](https://github.com/raeudigerRaeffi/generalizedReedSolomon/assets/21358654/aa462207-463d-4a90-a9bc-21e95f6ef887)

Prim poly is the same as the other parameters.
Why is this?
What should I tweak to get the same result?
Thanks.

**Comment by raeudigerRaeffi** [comment]
I have never used Matlab so I can not be of much help with regards to this one. Did you already try to corrupt a message and see whether the original message can successfully be recovered? If this works then there is probably a deviation from the initialization presented that you have not accounted for. If not then I would assume there is a mistake in the code

**Comment by DmitryYenkov** [comment]
Here is my reply on topic in this github project:
https://github.com/tomerfiliba-org/reedsolomon/issues/66

In your source code I just forcibly replaced polynom coefficients by those ones I needed and it worked.
![image](https://github.com/raeudigerRaeffi/generalizedReedSolomon/assets/21358654/0ea57e56-5579-47ab-a019-aef39c226592)

The replacement coefficient are:
TRUE_POLY_COEFFS = [[1, 118, 52, 103, 31, 104, 126, 187, 232, 17, 56, 183, 49, 100, 81, 44, 79]]
(list of lists, of size=1, cause p_factor is set to 1 for me.
