### ISSUE TITLE
Licence and collab?

### ISSUE THREAD

**Issue by lrq3000** [raeudigerRaeffi/generalizedReedSolomon#2]
Hello! I am the co-author and maintainer of one of, if not the, biggest Reed-Solomon codec for Python, at https://github.com/tomerfiliba-org/reedsolomon and also co-author of the Wikiversity tutorial on error correction codes.

I just discovered today your amazing work on this new type of parallelizable implementation of Reed-Solomon. I would be interested in trying to implement it as an option in reedsolomon (the package I maintain). But for this, I would need to ensure that your package has a compatible open-source licence.

Could you please create a LICENCE file and define a licence inside? If possible, a permissive licence such as MIT (which is what we use).

Please note I do not have any financial incentive in maintaining this project, it’s not in my domain at all, I do it only voluntarily because I am convinced an easy access to error correction code tools is essential to help other developers implement solutions that can prevent bit rot and the unavoidable massive loss of irreplaceable data (eg, most people take all their family pictures in digital format, but most of these are stored without redundancy and hence will be lost in max 20 years, if not before...).

Also, if you would be willing to join forces, we could work together in translating your implementation and then implement the last items in your todo :-)

BTW, did you hear about NTT? It’s an alternative method to FFT which is claimed to be more performant, maybe the Generalized RS could relatively easily be translated to use NTT?

**Comment by lrq3000** [comment]
For NTT (Number Theoretic Transform), here is a Reed-Solomon codec implementation using it but not in Python: https://github.com/Bulat-Ziganshin/FastECC

**Comment by raeudigerRaeffi** [comment]
Hi Stephen, thank you for your kind words, I actually started with your wikiversity article when I began working on this project :D. I have added the License file as requested by you. Regarding working together I would be interested in helping you merge my version into the library. I had plans to improve on this implementation anyways so this sounds like a good opportunity . To simplify communication you can contact me via e-mail at raffaelschoATgmail.com

**Comment by lrq3000** [comment]
@raeudigerRaeffi Oh wow, I am glad I could contribute to help you learn the basics, but your implementation far surpasses what I would have been able to do on my own 😄  Thank you so much for using a compatible open-source licence!!! I’ll send you an e-mail to talk abou the rest 😄
